// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/// @title ReferralRewards — BaseCast On-Chain Referral System
/// @notice Referrers earn a % of every wager placed by wallets they referred.
///         Rewards accrue here and are claimable at any time.
contract ReferralRewards is ReentrancyGuard {
    using SafeERC20 for IERC20;

    IERC20  public immutable usdc;
    address public owner;
    address public vault;          // Only GameVault can credit rewards

    /// @dev 100 bps = 1 %. Default 1 %, capped at 3 %.
    uint256 public rewardBps    = 100;
    uint256 public maxRewardBps = 300;

    /// referee  => their referrer (set once, immutable)
    mapping(address => address) public referrerOf;

    /// referrer => USDC claimable now
    mapping(address => uint256) public pendingRewards;

    /// referrer => lifetime USDC earned (includes already-claimed)
    mapping(address => uint256) public totalEarned;

    /// referrer => total wager volume generated by their referrals
    mapping(address => uint256) public totalVolumeReferred;

    /// referrer => number of unique wallets referred
    mapping(address => uint256) public referralCount;

    uint256 public totalAccrued;
    uint256 public totalPaidOut;

    // ── Events ─────────────────────────────────────────────────────────────
    event ReferralRegistered(address indexed referee, address indexed referrer);
    event RewardCredited(address indexed referrer, address indexed referee, uint256 wager, uint256 reward);
    event RewardClaimed(address indexed referrer, uint256 amount);
    event RewardsDeposited(uint256 amount);
    event RewardBpsUpdated(uint256 newBps);

    // ── Modifiers ──────────────────────────────────────────────────────────
    modifier onlyOwner() { require(msg.sender == owner, "Not owner"); _; }
    modifier onlyVault() { require(msg.sender == vault, "Not vault"); _; }

    // ── Constructor ────────────────────────────────────────────────────────
    /// @param _usdc  USDC token address
    /// @param _vault GameVault address (only caller allowed to credit rewards)
    constructor(address _usdc, address _vault) {
        require(_usdc  != address(0), "Zero usdc");
        require(_vault != address(0), "Zero vault");
        usdc  = IERC20(_usdc);
        vault = _vault;
        owner = msg.sender;
    }

    // ── Referee Registration ───────────────────────────────────────────────

    /// @notice Link your wallet to a referrer.
    ///         Call this once when you first join via a referral link.
    ///         Cannot self-refer. Cannot change referrer after registration.
    /// @param referrer The wallet address that referred you.
    function registerReferral(address referrer) external {
        require(referrer != address(0),   "Zero referrer");
        require(referrer != msg.sender,   "No self-referral");
        require(referrerOf[msg.sender] == address(0), "Already referred");

        referrerOf[msg.sender] = referrer;
        unchecked { referralCount[referrer]++; }
        emit ReferralRegistered(msg.sender, referrer);
    }

    // ── Called by GameVault ────────────────────────────────────────────────

    /// @notice Credit the referrer a % of the player's wager.
    ///         Called internally by GameVault.settleBet() — no direct user calls.
    /// @param player The player who just settled a bet.
    /// @param wager  The amount the player wagered (USDC, 6 decimals).
    function creditReward(address player, uint256 wager) external onlyVault {
        address referrer = referrerOf[player];
        if (referrer == address(0)) return;          // player has no referrer
        if (wager == 0) return;

        uint256 reward = (wager * rewardBps) / 10_000;
        if (reward == 0) return;

        unchecked {
            pendingRewards[referrer]          += reward;
            totalEarned[referrer]             += reward;
            totalVolumeReferred[referrer]     += wager;
            totalAccrued                      += reward;
        }

        emit RewardCredited(referrer, player, wager, reward);
    }

    // ── Claim ──────────────────────────────────────────────────────────────

    /// @notice Claim all your pending referral rewards in USDC.
    function claimRewards() external nonReentrant {
        uint256 amount = pendingRewards[msg.sender];
        require(amount > 0, "Nothing to claim");
        require(usdc.balanceOf(address(this)) >= amount, "Rewards pool empty - try again later");

        pendingRewards[msg.sender] = 0;
        unchecked { totalPaidOut += amount; }

        usdc.safeTransfer(msg.sender, amount);
        emit RewardClaimed(msg.sender, amount);
    }

    // ── Owner ──────────────────────────────────────────────────────────────

    /// @notice Deposit USDC to fund the rewards pool.
    ///         Owner must approve this contract to spend USDC first.
    function depositRewards(uint256 amount) external onlyOwner {
        usdc.safeTransferFrom(msg.sender, address(this), amount);
        emit RewardsDeposited(amount);
    }

    /// @notice Withdraw excess USDC from the rewards pool (emergency use).
    function withdrawRewards(uint256 amount) external onlyOwner nonReentrant {
        require(usdc.balanceOf(address(this)) >= amount, "Insufficient");
        usdc.safeTransfer(owner, amount);
    }

    /// @notice Set the reward rate. Max 3 % (300 bps).
    function setRewardBps(uint256 bps) external onlyOwner {
        require(bps <= maxRewardBps, "Exceeds max (300 bps)");
        rewardBps = bps;
        emit RewardBpsUpdated(bps);
    }

    /// @notice Update the vault address (e.g., after redeployment).
    function setVault(address _vault) external onlyOwner {
        require(_vault != address(0), "Zero");
        vault = _vault;
    }

    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Zero");
        owner = newOwner;
    }

    // ── Views ──────────────────────────────────────────────────────────────

    /// @notice USDC balance currently in the rewards pool.
    function poolBalance() external view returns (uint256) {
        return usdc.balanceOf(address(this));
    }

    /// @notice Snapshot of a referrer's stats.
    function getReferrerStats(address referrer) external view returns (
        uint256 pending,
        uint256 earned,
        uint256 volume,
        uint256 count
    ) {
        return (
            pendingRewards[referrer],
            totalEarned[referrer],
            totalVolumeReferred[referrer],
            referralCount[referrer]
        );
    }
}

